# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

competencies = [
  "3D Video",
  "3D Art",
  "Advertising",
  "Advertising Copy",
  "Affiliate Marketing",
  "Affiliates",
  "Android app",
  "Animation",
  "Animation Video",
  "App Design",
  "Articles",
  "Banner Ad Copy",
  "Banner Advertising"
  "Banner Advertising",
  "Billboard adverts",
  "Blog",
  "Book Illustration",
  "Brand Activation",
  "Brand Awareness",
  "Branding",
  "Brochure Copy",
  "Catalogue",
  "Commercial Photography",
  "Commercial Video",
  "Computer Graphics",
  "Copywriting",
  "CRM",
  "Cross-channel Marketing",
  "Customer Acquisition",
  "Data Analytics",
  "Database Development",
  "Design",
  "Design Strategy",
  "Desktop app",
  "Digital Advertising",
  "Digital Strategy",
  "Direct Mail marketing",
  "Display Advertising",
  "Display Design",
  "Documentary",
  "Drupal Development",
  "E-commerce",
  "Email marketing",
  "Educational Video",
  "Environmental Design",
  "Ergonomy",
  "Event",
  "Exhibition Banners",
  "Experiential Marketing",
  "Facebook Advertising",
  "Facebook Page",
  "Gaming",
  "Graphic Design",
  "Guerrilla Marketing",
  "Inbound marketing",
  "Industrial Design",
  "Infographic",
  "Innovation",
  "Iphone app",
  "Journalism",
  "Layout Design",
  "Linkedin advertising",
  "Local search marketing",
  "Logo Design",
  "Magazine adverts",
  "Marketing",
  "Marketing automation",
  "Marketing Copy",
  "Marketing email",
  "Marketing Strategy",
  "Media",
  "Media Planning",
  "Merchandise",
  "Mobile",
  "Mobile advertising",
  "Mobile App Development",
  "Mobile Marketing",
  "Mobile software development",
  "Multi Channel Strategy",
  "Music Video",
  "Newsletter",
  "Online Advertising",
  "Online Content",
  "Pay per click",
  "Photography",
  "Point of Sale",
  "Positioning",
  "Postal mail",
  "PPC",
  "PR",
  "Presentation video",
  "Press Releases",
  "Print",
  "Print Advertising",
  "Print Services",
  "Product Advertising",
  "Product Design",
  "Product Photography",
  "Promotions",
  "Public Relations",
  "Publication & Print Design",
  "Qualitative Insights",
  "Quantitative Insights",
  "Radio",
  "Reports",
  "Responsive",
  "Retargeting",
  "Script Writing",
  "Search",
  "Search engine optimisation",
  "SEA",
  "SEO",
  "Shopper Marketing",
  "Shorts Video",
  "Slogans & Straplines",
  "Social Media Marketing",
  "Stand Design",
  "Tablet",
  "Tablet App Development",
  "Training Video",
  "Transactional email",
  "Translating services",
  "Translation",
  "TV Advertising",
  "Twitter Advertising",
  "Typography",
  "User experience",
  "User Interface",
  "UX & UI",
  "Video Design",
  "Video Editing",
  "Video Production",
  "Video Publishing",
  "Viral Marketing",
  "Web App Development",
  "Web Design",
  "Web Programming",
  "Web Shop",
  "Website",
  "Website Analytics",
  "Website CMS",
  "Website Copy",
  "Website Design",
  "Website Development",
  "Website for Mobile & Tablet",
  "Internet site",
  "Internet site Analytics",
  "Internet site CMS",
  "Internet site Copy",
  "Internet site Design",
  "Internet site Development",
  "Internet site for Mobile & Tablet",
  "White Papers Copy",
  "Word of Mouth",
  "Wordpress builder",
  "Writing services",
  "Youtube channel manager",
  "Lead Management",
  "Contest",
  "Community Management",
  "Content Creation",
  "IOS builder",
  "Windows app builder",
  "Data Marketing",
  "Data Reporting",
  "Ads manager",
  "Publicity",
  "Advertisement",
  "Billboard",
  "Magazine",
  "Brand Image",
  "Brand my company",
  "Brand my product",
  "Packaging",
  "Motion Design",
  "Video Clip",
  "Video Youtube",
  "Video Presentation",
  "Digital Business Integration",
  "E-mailing Strategy",
  "Advertising Campaign",
  "Postcard Mailing",
  "E-Shopping",
  "Sell Online",
  "Event Marketing",
  "Event Strategy",
  "Exposition Planning",
  "Exhibition Planning",
  "Brand Promotion",
  "Promotion of my Website",
  "Acquire New Clients",
  "Redesign my Logo",
  "Explain my Concept with Video",
  "Present my Business in Video",
  "Reduce my Spam Score",
  "Improve the E-reputation of my Brand",
  "Get found on Google",
  "Get found on Apple Store",
  "Get the right Company Image",
  "Be in the press",
  "Augmented Reality",
  "Serious gaming",
  "Explain my concept with Content Strategy",
  "Enhance my customer loyalty with a new Design",
  "Adapt my Branding to a new market",
  "Retain customer with a good Content Strategy",
  "Refresh my brand with a new Design",
  "Refresh my brand with professional Videos",
  "Use a professionel Video to explain my new concept",
  "Attract new clients with Mobile devices",
  "Revise my Branding",
  "Convince more clients with Branding",
  "Rethink my Digital Strategy",
  "Attract new client with Content strategy",
  "Reach more customers thanks to E-commerce",
  "Attract more clients thanks to Online Ads",
  "Use a Digital Strategy to launch my new concept",
  "Develop a media presence through Public Relation",
  "Reach new market thanks to Advertising",
  "Work on my SEO",
  "Increase my visibility with Online Ads",
  "Build my Website",
  "Refresh my Content Strategy",
  "Use Content Strategy to reach customers in a new market",
  "Adapt my Design to a new market",
  "Use Digital Strategy to enter a new market",
  "Be on Mobile devices",
  "Power my brand with Brand activation",
  "Think",
  "Sell online with an E-commerce platform",
  "Advertise my new concept with Online ads",
  "Convert more customers thanks to great User Experience",
  "Improve brand loyalty with a new Branding",
  "Think of an effective Digital Strategy in order to retain customers",
  "Work on my Content Strategy",
  "Enter new markets thanks to Public Relation",
  "Use professional Videos to adress a new market",
  "Convince more clients with Videos",
  "Retain customer with a professional Website",
  "Adapt my Website to a new market",
  "Launch my new concept with a Website",
  "Launch a product with a brand activation campaign",
  "Outperfom thanks to Web Analytics",
  "Brand my concept",
  "Work on my Branding",
  "Improve my User Experience",
  "Stay in-touch with customers thanks to Brand Activation activities",
  "Use Brand Activation on a new market",
  "Launch my new concept using Brand Activation",
  "Reach new client thanks to Brand Activation",
  "Keep my customers active with Online Ads",
  "Revitalize my brand thanks to Online ads",
  "Adress a new market with Online Ads",
  "Invest in Big Data",
  "Stay a key player thanks to SEO",
  "Give my brand a better chance with a good SEO",
  "Use SEO to compete in a new market",
  "Better understand customers thanks to Web Analytics",
  "Introduce my new concept thanks Social Media Marketing",
  "Reach a greater audience thanks to Advertising",
  "Use Public Relation to revitalize my media relations",
  "Use Public Relation to present my new concept",
  "Use professional Videos to retain customers",
  "Retain customer with a coherent Mobile Strategy",
  "Adapt my Mobile Strategy to a new market",
  "Use Social Media Marketing to retain customer",
  "Use Advertising to introduce a new concept to customers",
  "Improve customer loyalty with an Email Strategy",
  "Enter a new market with an Email Strategy",
  "Launch my new concept on Mobile devices",
  "Renew my brand with a professional Website",
  "Create a powerfull brand identity",
  "Build customer loyalty with great Advertising",
  "Assess my business performance in a new market with Web Analytics",
  "Understand customers behaviours thanks to Web Analytics",
  "Refresh my communication with a new Email Strategy",
  "Design my new concept effectively",
  "Measure the validity of my new concept thanks to Web Analytics",
  "Revive my brand with Social Media Marketing",
  "Use Email Strategy to launch a new concept",
  "Gain new clients thanks to Social Media Marketing",
  "Use Public Relation to acquire new clients",
  "Attract more clients thanks to SEO",
  "Communicate with the media",
  "Reach new clients thanks to Email Strategy",
  "Enter a new market thanks to Social media Marketing",
  "Use Web Analytics to understand where you loose customers",
  "Revive my brand with a Brand Activation",
  "Make sure my Mobile Strategy is well adapted",
  "Adapt the User Experience to a new market",
  "Stay in-touch with my audience thanks to Public Relation",
  "Optimize my digital strategy",
  "Attract more client thanks to my Website",
  "Retain customer with an effective Ecommerce",
  "Revive my business with an effective Ecommerce",
  "Rethink my User Experience",
  "Make sure my new concept has a positive User experience",
  "Revitalize my brand with Creative Advertising",
  "Retain my clients thanks to great User experience",
  "Get found on Google",
  "Sell my products online",
  "Invest in Creative Advertising",
  "Use Video to support my business",
  "Be on Social Media",
  "Attract new clients thanks to great Design",
  "Get more client thanks to Digital Strategy",
  "Adapt my Ecommerce to a new market",
  "Use E-commerce to sell my new concept",
  "Develop a mobile app",
  "Create a movie clip",
  "Organize a marketing event",
  "Set up an emailing strategy",
  "Build a cross-media advertising campaign",
  "Create a website",
  "Desktop application",
  "Android application",
  "Application Design",
  "iPhone application",
  "ios app",
  "ios application",
  "mobile application development",
  "tablet application development",
  "ipad app development",
  "ipad application development",
  "web application development",
  "windows phone application",
  "windows application builder",
  "develop a mobile application",
  "Online Advertising",
  "RTB (real-time bidding)",
  "Programmatic",
  "Display advertising",
  "Affiliate marketing",
  "Social media Ads",
  "Mobile advertising",
  "Email advertising",
  "Chat advertising",
  "Adware",
  "Interstitial",
  "Content Marketing",
  "Bannering",
  "Pop-ups",
  "Feed ads",
  "Track banners",
  "Floating ad",
  "Frame ad",
  "Web banner advertising",
  "Web banner advertising",
  "Lead generation",
  "Marketing Automation",
  "Cross-channel Marketing",
  "Customer Acquisition",
  "Digital Advertising",
  "Facebook Advertising",
  "Pay per click",
  "Geomarketing",
  "Retargeting",
  "Twitter Advertising",
  "Linkedin Advertising",
  "Facebook Advertising",
  "Ads manager",
  "Search Engine Advertising (SEA)",
  "Google Display Network (GDN)",
  "YouTube",
  "Google Shopping",
  "Retargeting",
  "Dynamic Retargeting"]
]
